[build]
  publish = "."
  functions = "netlify/functions"

# --- APIs del front ---
[[redirects]]
  from = "/api/weather"
  to   = "/.netlify/functions/weather"
  status = 200

[[redirects]]
  from = "/api/forecast"
  to   = "/.netlify/functions/forecast"
  status = 200

[[redirects]]
  from = "/api/log-rain"
  to   = "/.netlify/functions/log-rain"
  status = 200

# Descarga directa de CSV
[[redirects]]
  from = "/logs.csv"
  to   = "/.netlify/functions/logs-csv"
  status = 200
  force = true
