[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

# ruta “amigable” para el botón Exportar
[[redirects]]
  from = "/logs-csv.csv"
  to = "/.netlify/functions/logs-csv"
  status = 200
  force = true
