[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/weather"
  to   = "/.netlify/functions/weather"
  status = 200

[[redirects]]
  from = "/api/forecast"
  to   = "/.netlify/functions/forecast"
  status = 200

[[redirects]]
  from = "/api/logRain"
  to   = "/.netlify/functions/logRain"
  status = 200

[[redirects]]
  from = "/api/logsCsv"
  to   = "/.netlify/functions/logsCsv"
  status = 200
